/* tslint:disable */
/* eslint-disable */
/**
 * LobbyLeaks API
 * Endpoint JSON‑RPC 2.0 (`/rpc2`) con cuatro acciones stub que devuelven 501 mientras el MVP está en desarrollo.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface EntityResult
 */
export interface EntityResult {
    /**
     *
     * @type {string}
     * @memberof EntityResult
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof EntityResult
     */
    type: EntityResultTypeEnum;
    /**
     *
     * @type {string}
     * @memberof EntityResult
     */
    label: string;
    /**
     *
     * @type {string}
     * @memberof EntityResult
     */
    rut?: string | null;
}


/**
 * @export
 */
export const EntityResultTypeEnum = {
    Person: 'person',
    Organisation: 'organisation'
} as const;
export type EntityResultTypeEnum = typeof EntityResultTypeEnum[keyof typeof EntityResultTypeEnum];


/**
 * Check if a given object implements the EntityResult interface.
 */
export function instanceOfEntityResult(value: object): value is EntityResult {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    return true;
}

export function EntityResultFromJSON(json: any): EntityResult {
    return EntityResultFromJSONTyped(json, false);
}

export function EntityResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntityResult {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'type': json['type'],
        'label': json['label'],
        'rut': json['rut'] == null ? undefined : json['rut'],
    };
}

export function EntityResultToJSON(json: any): EntityResult {
    return EntityResultToJSONTyped(json, false);
}

export function EntityResultToJSONTyped(value?: EntityResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'id': value['id'],
        'type': value['type'],
        'label': value['label'],
        'rut': value['rut'],
    };
}

