/* tslint:disable */
/* eslint-disable */
/**
 * LobbyLeaks RPC API
 * Endpoint JSON‑RPC 2.0 (`/rpc2`) con cuatro acciones stub que devuelven 501 mientras el MVP está en desarrollo. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Error501
 */
export interface Error501 {
    /**
     * 
     * @type {string}
     * @memberof Error501
     */
    detail: string;
}

/**
 * Check if a given object implements the Error501 interface.
 */
export function instanceOfError501(value: object): value is Error501 {
    if (!('detail' in value) || value['detail'] === undefined) return false;
    return true;
}

export function Error501FromJSON(json: any): Error501 {
    return Error501FromJSONTyped(json, false);
}

export function Error501FromJSONTyped(json: any, ignoreDiscriminator: boolean): Error501 {
    if (json == null) {
        return json;
    }
    return {
        
        'detail': json['detail'],
    };
}

export function Error501ToJSON(json: any): Error501 {
    return Error501ToJSONTyped(json, false);
}

export function Error501ToJSONTyped(value?: Error501 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'detail': value['detail'],
    };
}

