/* tslint:disable */
/* eslint-disable */
/**
 * LobbyLeaks RPC API
 * Endpoint JSON‑RPC 2.0 (`/rpc2`) con cuatro acciones stub que devuelven 501 mientras el MVP está en desarrollo. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Error400
 */
export interface Error400 {
    /**
     * 
     * @type {string}
     * @memberof Error400
     */
    detail: string;
}

/**
 * Check if a given object implements the Error400 interface.
 */
export function instanceOfError400(value: object): value is Error400 {
    if (!('detail' in value) || value['detail'] === undefined) return false;
    return true;
}

export function Error400FromJSON(json: any): Error400 {
    return Error400FromJSONTyped(json, false);
}

export function Error400FromJSONTyped(json: any, ignoreDiscriminator: boolean): Error400 {
    if (json == null) {
        return json;
    }
    return {
        
        'detail': json['detail'],
    };
}

export function Error400ToJSON(json: any): Error400 {
    return Error400ToJSONTyped(json, false);
}

export function Error400ToJSONTyped(value?: Error400 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'detail': value['detail'],
    };
}

