/* tslint:disable */
/* eslint-disable */
/**
 * LobbyLeaks API
 * Endpoint JSON‑RPC 2.0 (`/rpc2`) con cuatro acciones stub que devuelven 501 mientras el MVP está en desarrollo. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GraphLink } from './GraphLink';
import {
    GraphLinkFromJSON,
    GraphLinkFromJSONTyped,
    GraphLinkToJSON,
    GraphLinkToJSONTyped,
} from './GraphLink';
import type { GraphNode } from './GraphNode';
import {
    GraphNodeFromJSON,
    GraphNodeFromJSONTyped,
    GraphNodeToJSON,
    GraphNodeToJSONTyped,
} from './GraphNode';

/**
 * 
 * @export
 * @interface GraphResponse
 */
export interface GraphResponse {
    /**
     * Echo of the requested center node id
     * @type {string}
     * @memberof GraphResponse
     */
    center: string;
    /**
     * 
     * @type {number}
     * @memberof GraphResponse
     */
    depth: number;
    /**
     * True when the center has more direct events than `limit_events`
     * @type {boolean}
     * @memberof GraphResponse
     */
    truncated: boolean;
    /**
     * 
     * @type {Array<GraphNode>}
     * @memberof GraphResponse
     */
    nodes: Array<GraphNode>;
    /**
     * 
     * @type {Array<GraphLink>}
     * @memberof GraphResponse
     */
    links: Array<GraphLink>;
}

/**
 * Check if a given object implements the GraphResponse interface.
 */
export function instanceOfGraphResponse(value: object): value is GraphResponse {
    if (!('center' in value) || value['center'] === undefined) return false;
    if (!('depth' in value) || value['depth'] === undefined) return false;
    if (!('truncated' in value) || value['truncated'] === undefined) return false;
    if (!('nodes' in value) || value['nodes'] === undefined) return false;
    if (!('links' in value) || value['links'] === undefined) return false;
    return true;
}

export function GraphResponseFromJSON(json: any): GraphResponse {
    return GraphResponseFromJSONTyped(json, false);
}

export function GraphResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GraphResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'center': json['center'],
        'depth': json['depth'],
        'truncated': json['truncated'],
        'nodes': ((json['nodes'] as Array<any>).map(GraphNodeFromJSON)),
        'links': ((json['links'] as Array<any>).map(GraphLinkFromJSON)),
    };
}

export function GraphResponseToJSON(json: any): GraphResponse {
    return GraphResponseToJSONTyped(json, false);
}

export function GraphResponseToJSONTyped(value?: GraphResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'center': value['center'],
        'depth': value['depth'],
        'truncated': value['truncated'],
        'nodes': ((value['nodes'] as Array<any>).map(GraphNodeToJSON)),
        'links': ((value['links'] as Array<any>).map(GraphLinkToJSON)),
    };
}

