/* tslint:disable */
/* eslint-disable */
/**
 * LobbyLeaks API
 * Endpoint JSON‑RPC 2.0 (`/rpc2`) con cuatro acciones stub que devuelven 501 mientras el MVP está en desarrollo. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GraphLink
 */
export interface GraphLink {
    /**
     * Event id (graph is event-centric, source is always an event)
     * @type {string}
     * @memberof GraphLink
     */
    source: string;
    /**
     * Person or Organisation id
     * @type {string}
     * @memberof GraphLink
     */
    target: string;
    /**
     * Role the target plays in the source event
     * @type {string}
     * @memberof GraphLink
     */
    label: GraphLinkLabelEnum;
}


/**
 * @export
 */
export const GraphLinkLabelEnum = {
    Pasivo: 'PASIVO',
    Activo: 'ACTIVO',
    Representado: 'REPRESENTADO',
    Financiador: 'FINANCIADOR',
    Donante: 'DONANTE'
} as const;
export type GraphLinkLabelEnum = typeof GraphLinkLabelEnum[keyof typeof GraphLinkLabelEnum];


/**
 * Check if a given object implements the GraphLink interface.
 */
export function instanceOfGraphLink(value: object): value is GraphLink {
    if (!('source' in value) || value['source'] === undefined) return false;
    if (!('target' in value) || value['target'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    return true;
}

export function GraphLinkFromJSON(json: any): GraphLink {
    return GraphLinkFromJSONTyped(json, false);
}

export function GraphLinkFromJSONTyped(json: any, ignoreDiscriminator: boolean): GraphLink {
    if (json == null) {
        return json;
    }
    return {
        
        'source': json['source'],
        'target': json['target'],
        'label': json['label'],
    };
}

export function GraphLinkToJSON(json: any): GraphLink {
    return GraphLinkToJSONTyped(json, false);
}

export function GraphLinkToJSONTyped(value?: GraphLink | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'source': value['source'],
        'target': value['target'],
        'label': value['label'],
    };
}

