/* tslint:disable */
/* eslint-disable */
/**
 * LobbyLeaks API
 * Endpoint JSON‑RPC 2.0 (`/rpc2`) con cuatro acciones stub que devuelven 501 mientras el MVP está en desarrollo. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GraphNode
 */
export interface GraphNode {
    /**
     * 
     * @type {string}
     * @memberof GraphNode
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof GraphNode
     */
    type: GraphNodeTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof GraphNode
     */
    label: string;
}


/**
 * @export
 */
export const GraphNodeTypeEnum = {
    Person: 'person',
    Organisation: 'organisation',
    Event: 'event'
} as const;
export type GraphNodeTypeEnum = typeof GraphNodeTypeEnum[keyof typeof GraphNodeTypeEnum];


/**
 * Check if a given object implements the GraphNode interface.
 */
export function instanceOfGraphNode(value: object): value is GraphNode {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    return true;
}

export function GraphNodeFromJSON(json: any): GraphNode {
    return GraphNodeFromJSONTyped(json, false);
}

export function GraphNodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): GraphNode {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
        'label': json['label'],
    };
}

export function GraphNodeToJSON(json: any): GraphNode {
    return GraphNodeToJSONTyped(json, false);
}

export function GraphNodeToJSONTyped(value?: GraphNode | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'label': value['label'],
    };
}

