/* tslint:disable */
/* eslint-disable */
/**
 * LobbyLeaks RPC API
 * Endpoint JSON‑RPC 2.0 (`/rpc2`) con cuatro acciones stub que devuelven 501 mientras el MVP está en desarrollo. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type JSONRPCRequestId
 * 
 * @export
 */
export type JSONRPCRequestId = number | string;

export function JSONRPCRequestIdFromJSON(json: any): JSONRPCRequestId {
    return JSONRPCRequestIdFromJSONTyped(json, false);
}

export function JSONRPCRequestIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): JSONRPCRequestId {
    if (json == null) {
        return json;
    }

    return {} as any;
}

export function JSONRPCRequestIdToJSON(json: any): any {
    return JSONRPCRequestIdToJSONTyped(json, false);
}

export function JSONRPCRequestIdToJSONTyped(value?: JSONRPCRequestId | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {};
}

