/* tslint:disable */
/* eslint-disable */
/**
 * LobbyLeaks RPC API
 * Endpoint JSON‑RPC 2.0 (`/rpc2`) con cuatro acciones stub que devuelven 501 mientras el MVP está en desarrollo. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JSONRPCRequestParams
 */
export interface JSONRPCRequestParams {
    /**
     * 
     * @type {string}
     * @memberof JSONRPCRequestParams
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof JSONRPCRequestParams
     */
    fileId?: string;
    /**
     * 
     * @type {number}
     * @memberof JSONRPCRequestParams
     */
    maxWords?: number;
    /**
     * 
     * @type {string}
     * @memberof JSONRPCRequestParams
     */
    text?: string;
    /**
     * Código país (ej. CL)
     * @type {string}
     * @memberof JSONRPCRequestParams
     */
    jurisdiction?: string;
}

/**
 * Check if a given object implements the JSONRPCRequestParams interface.
 */
export function instanceOfJSONRPCRequestParams(value: object): value is JSONRPCRequestParams {
    return true;
}

export function JSONRPCRequestParamsFromJSON(json: any): JSONRPCRequestParams {
    return JSONRPCRequestParamsFromJSONTyped(json, false);
}

export function JSONRPCRequestParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): JSONRPCRequestParams {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'] == null ? undefined : json['url'],
        'fileId': json['file_id'] == null ? undefined : json['file_id'],
        'maxWords': json['max_words'] == null ? undefined : json['max_words'],
        'text': json['text'] == null ? undefined : json['text'],
        'jurisdiction': json['jurisdiction'] == null ? undefined : json['jurisdiction'],
    };
}

export function JSONRPCRequestParamsToJSON(json: any): JSONRPCRequestParams {
    return JSONRPCRequestParamsToJSONTyped(json, false);
}

export function JSONRPCRequestParamsToJSONTyped(value?: JSONRPCRequestParams | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
        'file_id': value['fileId'],
        'max_words': value['maxWords'],
        'text': value['text'],
        'jurisdiction': value['jurisdiction'],
    };
}

