/* tslint:disable */
/* eslint-disable */
/**
 * LobbyLeaks API
 * Endpoint JSON‑RPC 2.0 (`/rpc2`) con cuatro acciones stub que devuelven 501 mientras el MVP está en desarrollo. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EntityResult } from './EntityResult';
import {
    EntityResultFromJSON,
    EntityResultFromJSONTyped,
    EntityResultToJSON,
    EntityResultToJSONTyped,
} from './EntityResult';

/**
 * 
 * @export
 * @interface SearchResponse
 */
export interface SearchResponse {
    /**
     * 
     * @type {Array<EntityResult>}
     * @memberof SearchResponse
     */
    results: Array<EntityResult>;
    /**
     * 
     * @type {number}
     * @memberof SearchResponse
     */
    total: number;
}

/**
 * Check if a given object implements the SearchResponse interface.
 */
export function instanceOfSearchResponse(value: object): value is SearchResponse {
    if (!('results' in value) || value['results'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function SearchResponseFromJSON(json: any): SearchResponse {
    return SearchResponseFromJSONTyped(json, false);
}

export function SearchResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'results': ((json['results'] as Array<any>).map(EntityResultFromJSON)),
        'total': json['total'],
    };
}

export function SearchResponseToJSON(json: any): SearchResponse {
    return SearchResponseToJSONTyped(json, false);
}

export function SearchResponseToJSONTyped(value?: SearchResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'results': ((value['results'] as Array<any>).map(EntityResultToJSON)),
        'total': value['total'],
    };
}

