/* tslint:disable */
/* eslint-disable */
/**
 * LobbyLeaks API
 * Endpoint JSON‑RPC 2.0 (`/rpc2`) con cuatro acciones stub que devuelven 501 mientras el MVP está en desarrollo. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Error400,
  Error501,
  GraphResponse,
  JSONRPCRequest,
  SearchResponse,
} from '../models/index';
import {
    Error400FromJSON,
    Error400ToJSON,
    Error501FromJSON,
    Error501ToJSON,
    GraphResponseFromJSON,
    GraphResponseToJSON,
    JSONRPCRequestFromJSON,
    JSONRPCRequestToJSON,
    SearchResponseFromJSON,
    SearchResponseToJSON,
} from '../models/index';

export interface GraphSubgraphRequest {
    center: string;
    depth?: number;
    limitEvents?: number;
    tenant?: string;
    xTenantId?: string;
}

export interface Rpc2JsonRpcRequest {
    jSONRPCRequest: JSONRPCRequest;
}

export interface SearchEntitiesRequest {
    q: string;
    tenant?: string;
    limit?: number;
    xTenantId?: string;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Returns a subgraph of nodes + links centered on the given node id, sourced from the materialized views `mv_graph_nodes` and `mv_graph_links`. The graph is event-centric: every link goes `Event → Entity`, so two entities are always connected through one or more intermediate event nodes. 
     * Subgraph projection centered on an entity or event
     */
    async graphSubgraphRaw(requestParameters: GraphSubgraphRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GraphResponse>> {
        if (requestParameters['center'] == null) {
            throw new runtime.RequiredError(
                'center',
                'Required parameter "center" was null or undefined when calling graphSubgraph().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['center'] != null) {
            queryParameters['center'] = requestParameters['center'];
        }

        if (requestParameters['depth'] != null) {
            queryParameters['depth'] = requestParameters['depth'];
        }

        if (requestParameters['limitEvents'] != null) {
            queryParameters['limit_events'] = requestParameters['limitEvents'];
        }

        if (requestParameters['tenant'] != null) {
            queryParameters['tenant'] = requestParameters['tenant'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xTenantId'] != null) {
            headerParameters['X-Tenant-Id'] = String(requestParameters['xTenantId']);
        }


        let urlPath = `/api/v1/graph`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GraphResponseFromJSON(jsonValue));
    }

    /**
     * Returns a subgraph of nodes + links centered on the given node id, sourced from the materialized views `mv_graph_nodes` and `mv_graph_links`. The graph is event-centric: every link goes `Event → Entity`, so two entities are always connected through one or more intermediate event nodes. 
     * Subgraph projection centered on an entity or event
     */
    async graphSubgraph(requestParameters: GraphSubgraphRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GraphResponse> {
        const response = await this.graphSubgraphRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Envia un objeto JSON‑RPC 2.0 con `method` en {fetch_pdf, ocr_pdf, summarise_doc, entity_link}. Parámetro opcional `jurisdiction` (ISO 3166‑1 alpha‑2), por defecto `\"CL\"`. 
     * JSON‑RPC over HTTP
     */
    async rpc2JsonRpcRaw(requestParameters: Rpc2JsonRpcRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['jSONRPCRequest'] == null) {
            throw new runtime.RequiredError(
                'jSONRPCRequest',
                'Required parameter "jSONRPCRequest" was null or undefined when calling rpc2JsonRpc().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/rpc2`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: JSONRPCRequestToJSON(requestParameters['jSONRPCRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Envia un objeto JSON‑RPC 2.0 con `method` en {fetch_pdf, ocr_pdf, summarise_doc, entity_link}. Parámetro opcional `jurisdiction` (ISO 3166‑1 alpha‑2), por defecto `\"CL\"`. 
     * JSON‑RPC over HTTP
     */
    async rpc2JsonRpc(requestParameters: Rpc2JsonRpcRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.rpc2JsonRpcRaw(requestParameters, initOverrides);
    }

    /**
     * Case-insensitive search across Person and Organisation tables by normalizedName or rut. Tenant is required via query param or X-Tenant-Id header. 
     * Search persons and organisations by name or RUT
     */
    async searchEntitiesRaw(requestParameters: SearchEntitiesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SearchResponse>> {
        if (requestParameters['q'] == null) {
            throw new runtime.RequiredError(
                'q',
                'Required parameter "q" was null or undefined when calling searchEntities().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        if (requestParameters['tenant'] != null) {
            queryParameters['tenant'] = requestParameters['tenant'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xTenantId'] != null) {
            headerParameters['X-Tenant-Id'] = String(requestParameters['xTenantId']);
        }


        let urlPath = `/api/v1/search`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SearchResponseFromJSON(jsonValue));
    }

    /**
     * Case-insensitive search across Person and Organisation tables by normalizedName or rut. Tenant is required via query param or X-Tenant-Id header. 
     * Search persons and organisations by name or RUT
     */
    async searchEntities(requestParameters: SearchEntitiesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SearchResponse> {
        const response = await this.searchEntitiesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
